'use strict';
const missions=[
 {title:'เลือกมื้ออร่อย',goal:'คุณต้องการซื้อข้าวกล่องที่เลือกไว้ บอกพนักงานอย่างไร?',npc:36,answer:42,options:[42,44,47],tip:'この (kono) หมายถึง “นี้” ชี้สินค้าพร้อมพูดได้เลย',item:'🍱'},
 {title:'อุ่นข้าวก่อนกิน',goal:'คุณอยากให้พนักงานอุ่นข้าวกล่องให้ ตอบรับอย่างสุภาพ',npc:37,answer:43,options:[43,44,46],tip:'温める (atatameru) คืออุ่นอาหาร ตอบ はい、お願いします (Hai, onegaishimasu) เพื่อขอให้ช่วยอุ่น',item:'♨️'},
 {title:'ใช้ถุงของเราเอง',goal:'คุณพกถุงผ้ามาด้วย ต้องการปฏิเสธถุงจากร้าน',npc:38,answer:44,options:[45,44,42],tip:'いりません (irimasen) หมายถึง “ไม่ต้องการ” ใช้ปฏิเสธถุงอย่างสุภาพ',item:'🛍️'},
 {title:'ขอตะเกียบ',goal:'คุณจะกินคนเดียว ขอตะเกียบหนึ่งคู่',npc:39,answer:45,options:[47,43,45],tip:'一膳 (ichizen) ใช้นับตะเกียบหนึ่งคู่',item:'🥢'},
 {title:'จ่ายเงิน',goal:'คุณต้องการชำระด้วยบัตร บอกวิธีจ่ายเงิน',npc:40,answer:46,options:[46,42,44],tip:'カードで (kaado de) คือ “ด้วยบัตร” ร้านและบัตรแต่ละประเภทอาจรองรับต่างกัน',item:'💳'},
 {title:'รับใบเสร็จแล้วออกเดินทาง',goal:'คุณต้องการเก็บใบเสร็จไว้ ขอใบเสร็จจากพนักงาน',npc:41,answer:47,options:[43,45,47],tip:'レシート (reshiito) คือใบเสร็จ อย่าลืมขอบคุณก่อนออกจากร้าน!',item:'🧾'},
 {title:'ซื้อน้ำดื่ม',goal:'คุณอยากซื้อน้ำดื่ม ขอพนักงานอย่างไร?',npc:36,answer:14,options:[14,42,47],reply:72,tip:'水 (mizu) แปลว่าน้ำ ใช้ をください เพื่อขอสิ่งที่ต้องการ',item:'💧'},
 {title:'รับถุงเพิ่ม',goal:'ครั้งนี้คุณซื้อของหลายชิ้นและไม่ได้พกถุงมา บอกว่าต้องการถุง',npc:38,answer:75,options:[75,44,45],reply:72,tip:'いります (irimasu) คือ “ต้องการ” ต่างจาก いりません (irimasen) ที่แปลว่า “ไม่ต้องการ” ถุงอาจมีค่าใช้จ่าย',item:'🛍️'},
 {title:'เลือกของใกล้พนักงาน',goal:'สินค้าที่ต้องการอยู่ใกล้พนักงาน แต่ไกลจากคุณ ขอสิ่งนั้นอย่างไร?',npc:36,answer:65,options:[65,66,42],reply:72,tip:'それ (sore) ใช้ชี้สิ่งที่อยู่ใกล้ผู้ฟัง พูด それをください (Sore o kudasai) เพื่อขอสิ่งนั้น',item:'🍙'},
 {title:'เลือกของบนชั้นไกล',goal:'สินค้าที่ต้องการอยู่ไกลทั้งคุณและพนักงาน ชี้แล้วขอสิ่งโน้น',npc:36,answer:66,options:[66,65,42],reply:72,tip:'あれ (are) ใช้ชี้สิ่งที่อยู่ไกลทั้งผู้พูดและผู้ฟัง',item:'🥤'},
 {title:'ถามก่อนใช้บัตร',goal:'คุณยังไม่แน่ใจว่าร้านรับบัตรหรือไม่ ถามว่าจ่ายด้วยบัตรได้ไหม',npc:40,answer:24,options:[24,46,47],reply:52,tip:'カードで払えますか (kaado de haraemasu ka) เป็นคำถามว่าจ่ายด้วยบัตรได้ไหม ก่อนเลือกวิธีจ่าย',item:'💳'},
 {title:'ฟังไม่ทัน ขออีกครั้ง',goal:'คุณฟังคำถามเรื่องการชำระเงินไม่ทัน ขอให้พนักงานพูดอีกครั้ง',npc:40,answer:35,options:[35,46,44],reply:40,tip:'もう一度お願いします (mou ichido onegaishimasu) ใช้ขอให้พูดหรือทำอีกครั้งอย่างสุภาพ',item:'👂'}
];
function clerkScene(){return `<div class="clerk-scene" role="img" aria-label="พนักงานร้านสะดวกซื้อยืนอยู่หลังเคาน์เตอร์"><div class="scene-sign">TABI MART <small>24 HOURS</small></div><div class="scene-shelves">🍙 🥤 🍵<br>🍱 🥪 🍫</div><div class="clerk"><div class="clerk-hair"></div><div class="clerk-face"><i class="eye left"></i><i class="eye right"></i><i class="cheek left"></i><i class="cheek right"></i><i class="mouth"></i></div><div class="clerk-body"><span>たび</span></div><div class="clerk-arm"><div class="clerk-hand"></div></div></div><div class="scene-counter"><span id="counter-item">🍱</span><span class="register">▣</span></div><div class="clerk-caption" id="clerk-caption">สวัสดี! ยินดีต้อนรับค่ะ</div></div>`}
function animateClerk(speaking){const scene=$('.clerk-scene');if(scene)scene.classList.toggle('speaking',speaking)}
function stopClerkAudio(){if(currentAudio)currentAudio.pause();animateClerk(false)}

let adventure=null;
function gameBest(){const n=read('tabi-konbini-best-v2',0);return typeof n==='number'?n:0}
function initAdventure(){
 stopClerkAudio();
 $('#adventure').innerHTML=`<div class="game-intro"><div class="eyebrow">JAPAN ADVENTURE · STAGE 01</div><h2>ภารกิจแรก: แวะร้านสะดวกซื้อ</h2>${clerkScene()}<p>ซื้ออาหารและน้ำ เลือกสินค้า ขอถุงและตะเกียบ ฝึกจ่ายเงินและขอให้พูดซ้ำ<br>เลือกคำตอบภาษาญี่ปุ่นให้ตรงกับภารกิจ ${missions.length} ด่าน</p><div class="game-rules">✦ ผ่านครั้งแรกได้ 100 คะแนนต่อด่าน<br>💡 ดูคำแปลได้ ลดคะแนนด่านนั้น 20 คะแนน<br>↻ ตอบผิดลองใหม่ได้ ลดคะแนนครั้งละ 20 คะแนน</div><p>สถิติดีที่สุด: ${gameBest()} / ${missions.length*100}</p><button class="primary" id="adventure-start">เข้าร้าน เริ่มภารกิจ →</button><button class="answer" id="konbini-learn">ดูประโยคร้านสะดวกซื้อก่อน</button></div>`;
 $('#adventure-start').addEventListener('click',startAdventure);
 $('#konbini-learn').addEventListener('click',()=>{setMode('learn');document.querySelector('[data-category="konbini"]').click();$('#search').value='';render()});
}
function startAdventure(){adventure={step:0,score:0,penalty:0,hint:false,done:false};renderAdventure();speak(phrases[36].jp,true)}
function renderAdventure(){stopClerkAudio();const m=missions[adventure.step],npc=phrases[m.npc];
 $('#adventure').innerHTML=`<div class="game-board"><div class="quiz-meta"><span>🏪 ร้านสะดวกซื้อ · ด่าน ${adventure.step+1}/${missions.length}</span><strong>${adventure.score} คะแนน</strong></div><div class="progress"><span style="width:${adventure.step/missions.length*100}%"></span></div><h2>${m.item} ${m.title}</h2><p class="mission-goal">${m.goal}</p>${clerkScene()}<div class="npc-bubble"><span class="badge">พนักงานพูด</span><p class="jp" lang="ja">${npc.jp}</p><p class="romaji">${npc.romaji}</p><p class="npc-thai">${npc.reading}</p><p class="game-translation" hidden>${npc.meaning}</p><button class="listen" id="npc-listen">◖)) ฟังพนักงาน</button></div><h3 class="answer-heading">เลือกคำตอบของคุณ</h3><div class="answers">${shuffle(m.options).map(id=>{const p=phrases[id];return `<button class="answer game-answer" data-response="${id}"><span lang="ja">${p.jp}</span><small><span class="answer-romaji">${p.romaji}</span><span class="answer-thai">${p.reading}</span></small><span class="game-translation" hidden>${p.meaning}</span></button>`}).join('')}</div><button class="hint-button" id="game-hint">💡 ดูคำแปล (−20 คะแนน)</button><div id="game-feedback" role="status" aria-live="polite"></div><button class="primary" id="game-next" hidden>${adventure.step===missions.length-1?'รับผลภารกิจ':'ไปด่านถัดไป'} →</button><button class="hint-button" id="game-reset">เริ่มภารกิจใหม่</button></div>`;
 $('#npc-listen').addEventListener('click',()=>speak(npc.jp,true));
 document.querySelectorAll('[data-response]').forEach(b=>b.addEventListener('click',()=>respondAdventure(Number(b.dataset.response))));
 $('#game-hint').addEventListener('click',()=>{if(adventure.hint||adventure.done)return;adventure.hint=true;adventure.penalty+=20;document.querySelectorAll('.game-translation').forEach(x=>x.hidden=false);$('#game-hint').disabled=true;$('#game-hint').textContent='แสดงคำแปลแล้ว'});
 $('#game-next').addEventListener('click',()=>{adventure.step++;adventure.step===missions.length?finishAdventure():(adventure.penalty=0,adventure.hint=false,adventure.done=false,renderAdventure(),speak(phrases[missions[adventure.step].npc].jp,true))});
 $('#game-reset').addEventListener('click',initAdventure);
}
function respondAdventure(id){if(adventure.done)return;const m=missions[adventure.step],p=phrases[id],button=document.querySelector(`[data-response="${id}"]`);
 if(id!==m.answer){adventure.penalty+=20;button.disabled=true;button.classList.add('wrong');animateClerk(false);$('.clerk-scene').classList.remove('happy');$('#clerk-caption').textContent='ลองตอบใหม่ได้นะคะ';$('#game-feedback').textContent=`ลองใหม่ได้! ประโยคนี้หมายถึง “${p.meaning}” ยังไม่ตรงกับภารกิจ (−20 คะแนน)`;return}
 adventure.done=true;$('.clerk-scene').classList.add('happy');const reply=phrases[m.reply??(48+adventure.step)];$('#clerk-caption').textContent=reply.meaning;$('#counter-item').textContent=m.item;speak(reply.jp,true);const points=Math.max(0,100-adventure.penalty);adventure.score+=points;button.classList.add('correct');document.querySelectorAll('[data-response]').forEach(b=>b.disabled=true);$('#game-hint').disabled=true;
 $('#game-feedback').innerHTML=`<p>✓ สำเร็จ! +${points} คะแนน</p><div class="feedback-phrase"><p class="jp" lang="ja">${p.jp}</p><p class="romaji">${p.romaji}</p><p class="npc-thai">${p.reading}</p><p class="feedback-meaning">${p.meaning}</p></div><p>${m.tip}</p><div class="feedback-phrase"><span class="badge">พนักงานตอบกลับ</span><p class="jp" lang="ja">${reply.jp}</p><p class="romaji">${reply.romaji}</p><p class="npc-thai">${reply.reading}</p><p>${reply.meaning}</p><button class="listen" id="clerk-reply-listen">◖)) ฟังพนักงานตอบกลับ</button></div><button class="listen" id="reply-listen">◖)) ฟังคำตอบของคุณ</button>`;
 $('#clerk-reply-listen').addEventListener('click',()=>speak(reply.jp,true));$('#reply-listen').addEventListener('click',()=>speak(p.jp));$('#game-next').hidden=false;$('#game-next').focus();
}
function finishAdventure(){stopClerkAudio();const best=Math.max(gameBest(),adventure.score);write('tabi-konbini-best-v2',best);$('#adventure').innerHTML=`<div class="game-intro"><div class="eyebrow">STAGE 01 · COMPLETE</div><div class="game-trophy">${adventure.score>=missions.length*100*5/6?'🏆':adventure.score>=missions.length*100/2?'🌟':'🌸'}</div><h2>ซื้อของสำเร็จ พร้อมออกเที่ยว!</h2><div class="result-score">${adventure.score}<small> / ${missions.length*100}</small></div><p>ผ่านครบ ${missions.length} สถานการณ์ร้านสะดวกซื้อแล้ว<br>สถิติดีที่สุด: ${best} / ${missions.length*100}</p><p>ขอบคุณพนักงานด้วย ありがとうございます<br>Arigatou gozaimasu • อะริกาโต โกะไซมัส</p><button class="listen" id="thanks-listen">◖)) ฟังคำขอบคุณ</button><p><button class="primary" id="adventure-again">เล่นอีกครั้ง →</button></p><button class="answer" id="game-home">กลับหน้าภารกิจ</button></div>`;$('#adventure-again').addEventListener('click',startAdventure);$('#game-home').addEventListener('click',initAdventure);$('#thanks-listen').addEventListener('click',()=>speak(phrases[1].jp))}

