'use strict';
const categories=[['all','✦','ทั้งหมด'],['konbini','🏪','ร้านสะดวกซื้อ'],['basics','👋','คำพื้นฐาน'],['transport','🚃','เดินทาง'],['food','🍜','ร้านอาหาร'],['hotel','🏡','ที่พัก'],['shopping','🛍','ช้อปปิ้ง'],['help','🧭','ขอความช่วยเหลือ']];
const rows=[
['basics','こんにちは','คอนนิจิวะ','สวัสดี'],['basics','ありがとうございます','อะริกาโต โกะไซมัส','ขอบคุณ'],['basics','すみません','ซุมิมาเซ็น','ขอโทษ / ขอรบกวน'],['basics','はい','ไฮ','ใช่ / ครับ / ค่ะ'],['basics','いいえ','อีเอะ','ไม่ใช่'],['basics','日本語がわかりません','นิฮงโกะ กะ วะคะริมะเซ็น','ไม่เข้าใจภาษาญี่ปุ่น'],
['transport','駅はどこですか','เอะคิ วะ โดะโคะ เดสกะ','สถานีอยู่ที่ไหน'],['transport','この電車は東京に行きますか','โคะโนะ เด็นฉะ วะ โตเกียว นิ อิคิมัสกะ','รถไฟขบวนนี้ไปโตเกียวไหม'],['transport','切符を一枚ください','คิปปุ โอะ อิจิไม คุดะไซ','ขอตั๋วหนึ่งใบ'],['transport','空港までお願いします','คูโค มะเดะ โอะเนะไกชิมัส','กรุณาไปส่งที่สนามบิน'],['transport','ここで降ります','โคะโคะ เดะ โอะริมาส','จะลงตรงนี้'],['transport','いくらですか','อิคุระ เดสกะ','ราคาเท่าไหร่'],
['food','メニューをください','เมนิว โอะ คุดะไซ','ขอเมนูหน่อย'],['food','これをください','โคะเระ โอะ คุดะไซ','ขออันนี้'],['food','水をください','มิซุ โอะ คุดะไซ','ขอน้ำหน่อย'],['food','おすすめは何ですか','โอะซุซุเมะ วะ นัน เดสกะ','มีอะไรแนะนำบ้าง'],['food','お会計をお願いします','โอะไคเค โอะ โอะเนะไกชิมัส','ขอเช็กบิล'],['food','卵アレルギーがあります','ทะมะโกะ อะเระรุกี กะ อะริมัส','ฉันแพ้ไข่'],
['hotel','チェックインをお願いします','เช็กคุอิน โอะ โอะเนะไกชิมัส','ขอเช็กอิน'],['hotel','予約しています','โยะยะคุ ชิเตอิมัส','จองไว้แล้ว'],['hotel','荷物を預かってもらえますか','นิโมะทสึ โอะ อะซุคัตเตะ โมะระเอะมัสกะ','ฝากกระเป๋าได้ไหม'],['hotel','朝食は何時ですか','โชโชะคุ วะ นันจิ เดสกะ','อาหารเช้ากี่โมง'],['hotel','Wi-Fiのパスワードは何ですか','ไวไฟ โนะ พะสุวาโดะ วะ นัน เดสกะ','รหัสผ่าน Wi-Fi คืออะไร'],['hotel','チェックアウトは何時ですか','เช็กคุเอาโตะ วะ นันจิ เดสกะ','เช็กเอาต์กี่โมง'],
['shopping','カードで払えますか','คาโดะ เดะ ฮะระเอะมัสกะ','จ่ายด้วยบัตรได้ไหม'],['shopping','免税できますか','เม็นเซ เดะคิมัสกะ','ทำเรื่องยกเว้นภาษีได้ไหม'],['shopping','袋をください','ฟุคุโระ โอะ คุดะไซ','ขอถุงหน่อย'],['shopping','試着してもいいですか','ชิฉะคุ ชิเตะโมะ อี เดสกะ','ลองสวมได้ไหม'],['shopping','小さいサイズはありますか','ชีไซ ไซซุ วะ อะริมัสกะ','มีไซซ์เล็กไหม'],['shopping','見ているだけです','มิเตอิรุ ดะเคะ เดส','ขอดูก่อน'],
['help','トイレはどこですか','โทะอิเระ วะ โดะโคะ เดสกะ','ห้องน้ำอยู่ที่ไหน'],['help','助けてください','ทะสุเคะเตะ คุดะไซ','ช่วยด้วย'],['help','道に迷いました','มิจิ นิ มะโยะอิมะชิตะ','ฉันหลงทาง'],['help','病院はどこですか','เบียวอิน วะ โดะโคะ เดสกะ','โรงพยาบาลอยู่ที่ไหน'],['help','ゆっくり話してください','ยุคคุริ ฮะนะชิเตะ คุดะไซ','ช่วยพูดช้า ๆ'],['help','もう一度お願いします','โม อิจิโดะ โอะเนะไกชิมัส','ขออีกครั้งได้ไหม']];
rows.push(...[["konbini", "いらっしゃいませ", "อิรัชชัยมาเซะ", "ยินดีต้อนรับ"], ["konbini", "お弁当を温めますか", "โอะเบ็นโต โอะ อะทะทะเมะมัสกะ", "ให้อุ่นข้าวกล่องไหม"], ["konbini", "レジ袋はご利用ですか", "เระจิบุคุโระ วะ โกะริโย เดสกะ", "รับถุงใส่สินค้าไหม"], ["konbini", "お箸は何膳お付けしますか", "โอะฮะชิ วะ นันเซ็น โอะทสึเคะชิมัสกะ", "รับตะเกียบกี่คู่"], ["konbini", "お支払いはどうなさいますか", "โอะชิฮะไร วะ โด นะไซมัสกะ", "จะชำระเงินด้วยวิธีไหน"], ["konbini", "レシートはご入用ですか", "เระชีโตะ วะ โกะอิริโย เดสกะ", "ต้องการใบเสร็จไหม"], ["konbini", "このお弁当をください", "โคะโนะ โอะเบ็นโต โอะ คุดะไซ", "ขอข้าวกล่องนี้"], ["konbini", "はい、お願いします", "ไฮ โอะเนะไกชิมัส", "รับครับ/ค่ะ รบกวนด้วย"], ["konbini", "袋はいりません", "ฟุคุโระ วะ อิริมาเซ็น", "ไม่รับถุง"], ["konbini", "お箸を一膳ください", "โอะฮะชิ โอะ อิจิเซ็น คุดะไซ", "ขอตะเกียบหนึ่งคู่"], ["konbini", "カードでお願いします", "คาโดะ เดะ โอะเนะไกชิมัส", "ขอจ่ายด้วยบัตร"], ["konbini", "レシートをください", "เระชีโตะ โอะ คุดะไซ", "ขอใบเสร็จ"]]);
const romaji=["Konnichiwa", "Arigatou gozaimasu", "Sumimasen", "Hai", "Iie", "Nihongo ga wakarimasen", "Eki wa doko desu ka", "Kono densha wa Toukyou ni ikimasu ka", "Kippu o ichimai kudasai", "Kuukou made onegaishimasu", "Koko de orimasu", "Ikura desu ka", "Menyuu o kudasai", "Kore o kudasai", "Mizu o kudasai", "Osusume wa nan desu ka", "Okaikei o onegaishimasu", "Tamago arerugii ga arimasu", "Chekkuin o onegaishimasu", "Yoyaku shite imasu", "Nimotsu o azukatte moraemasu ka", "Choushoku wa nanji desu ka", "Waifai no pasuwaado wa nan desu ka", "Chekkuauto wa nanji desu ka", "Kaado de haraemasu ka", "Menzei dekimasu ka", "Fukuro o kudasai", "Shichaku shite mo ii desu ka", "Chiisai saizu wa arimasu ka", "Mite iru dake desu", "Toire wa doko desu ka", "Tasukete kudasai", "Michi ni mayoimashita", "Byouin wa doko desu ka", "Yukkuri hanashite kudasai", "Mou ichido onegaishimasu"];
romaji.push(...["Irasshaimase", "Obentou o atatamemasu ka", "Rejibukuro wa goriyou desu ka", "Ohashi wa nanzen otsuke shimasu ka", "Oshiharai wa dou nasaimasu ka", "Reshiito wa goiriyou desu ka", "Kono obentou o kudasai", "Hai, onegaishimasu", "Fukuro wa irimasen", "Ohashi o ichizen kudasai", "Kaado de onegaishimasu", "Reshiito o kudasai"]);
rows.push(...[["konbini", "こちらのお弁当ですね。", "โคะจิระ โนะ โอะเบ็นโต เดสเนะ", "รับข้าวกล่องนี้นะคะ"], ["konbini", "かしこまりました。温めます。", "คะชิโคะมะริมะชิตะ อะทะทะเมะมัส", "รับทราบค่ะ จะอุ่นให้ค่ะ"], ["konbini", "袋なしですね。", "ฟุคุโระ นะชิ เดสเนะ", "ไม่รับถุงนะคะ"], ["konbini", "お箸を一膳お付けします。", "โอะฮะชิ โอะ อิจิเซ็น โอะทสึเคะชิมัส", "จะใส่ตะเกียบให้หนึ่งคู่ค่ะ"], ["konbini", "カードをこちらにお願いします。", "คาโดะ โอะ โคะจิระ นิ โอะเนะไกชิมัส", "กรุณาใช้บัตรที่เครื่องนี้ค่ะ"], ["konbini", "レシートです。ありがとうございました。", "เระชีโตะ เดส อะริกาโต โกะไซมะชิตะ", "นี่ใบเสร็จค่ะ ขอบคุณที่ใช้บริการค่ะ"]]);
romaji.push(...["Kochira no obentou desu ne.", "Kashikomarimashita. Atatamemasu.", "Fukuro nashi desu ne.", "Ohashi o ichizen otsuke shimasu.", "Kaado o kochira ni onegaishimasu.", "Reshiito desu. Arigatou gozaimashita."]);
const phrases=rows.map((r,id)=>({id,category:r[0],jp:r[1],reading:r[2],meaning:r[3],romaji:romaji[id]}));
const $=s=>document.querySelector(s);
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{notify('เครื่องนี้ไม่สามารถบันทึกข้อมูลได้ แต่ยังฝึกต่อได้')}}
const stored=read('tabi-saved',[]);let saved=new Set(Array.isArray(stored)?stored.filter(id=>phrases.some(p=>p.id===id)):[]),mode='learn',category='all',quiz=null,utterance=null,timer;
function notify(message){$('#status').textContent=message;clearTimeout(timer);timer=setTimeout(()=>$('#status').textContent='',4500)}
function label(cat){return categories.find(c=>c[0]===cat)[2]}
function render(){
 $('#saved-count').textContent=saved.size;$('#list-title').textContent=mode==='saved'?'ประโยคที่เก็บไว้ใช้ระหว่างเที่ยว':'วันนี้อยากฝึกเรื่องอะไร?';
 const query=$('#search').value.trim().toLowerCase();const filtered=phrases.filter(p=>(mode!=='saved'||saved.has(p.id))&&(category==='all'||category===p.category)&&[p.jp,p.reading,p.meaning,p.romaji].some(v=>v.toLowerCase().includes(query)));
 $('#result-count').textContent=`${filtered.length} ประโยค • แตะฟัง แล้วลองพูดตาม`;
 $('#cards').innerHTML=filtered.length?filtered.map(p=>`<article class="card"><div class="card-top"><span class="badge">${label(p.category)}</span><button class="save" data-save="${p.id}" aria-pressed="${saved.has(p.id)}" aria-label="${saved.has(p.id)?'ลบ':'บันทึก'}ประโยคโปรด: ${p.meaning}">${saved.has(p.id)?'♥':'♡'}</button></div><h3 class="jp" lang="ja">${p.jp}</h3><p class="romaji" lang="en" style="color:#737b70;font-size:13px;margin:0 0 8px;overflow-wrap:anywhere">${p.romaji}</p><p class="reading">${p.reading}</p><p class="meaning">${p.meaning}</p><button class="listen" data-listen="${p.id}" aria-label="ฟังเสียง: ${p.meaning}">◖)) <span>ฟังเสียงญี่ปุ่น</span></button></article>`).join(''):'<p class="empty">ยังไม่มีประโยคที่ตรงกับเงื่อนไข ลองเปลี่ยนหมวดหรือค้นหาใหม่ได้เลย</p>';
}
function setMode(next){if(next!=='game')stopClerkAudio();mode=next;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode))});$('#learn-panel').hidden=mode!=='learn'&&mode!=='saved';$('#quiz-panel').hidden=mode!=='quiz';$('#adventure-panel').hidden=mode!=='game';if(mode==='learn'||mode==='saved')render();else if(mode==='quiz')bestScore()}
$('#categories').innerHTML=categories.map(([id,icon,name])=>`<button data-category="${id}" class="${id==='all'?'active':''}" aria-pressed="${id==='all'}">${icon} ${name}</button>`).join('');
$('#quiz-category').innerHTML=categories.map(([id,icon,name])=>`<option value="${id}">${icon} ${name}</option>`).join('');
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render()});
$('#search').addEventListener('input',render);
$('#cards').addEventListener('click',e=>{const save=e.target.closest('[data-save]'),listen=e.target.closest('[data-listen]');if(save){const id=Number(save.dataset.save);saved.has(id)?saved.delete(id):saved.add(id);write('tabi-saved',[...saved]);render();const restored=document.querySelector(`[data-save="${id}"]`);if(restored)restored.focus();else $('#list-title').scrollIntoView({block:'nearest'})}if(listen)speak(phrases[Number(listen.dataset.listen)].jp)});
let currentAudio=null,playbackSpeed=1;
function togglePlaybackSpeed(){
 playbackSpeed=playbackSpeed===1?0.8:1;
 const slow=playbackSpeed!==1;
 $('#slow-toggle').setAttribute('aria-pressed',String(slow));
 $('#slow-toggle').textContent=slow?'ใช้ความเร็วปกติ':'ฟังช้า';
 $('#speed-label').textContent=slow?'ความเร็วเสียง: ช้า (0.8×)':'ความเร็วเสียง: ปกติ';
 if(currentAudio)currentAudio.playbackRate=playbackSpeed;
}
$('#slow-toggle').addEventListener('click',togglePlaybackSpeed);
function speak(text,clerk=false){
 animateClerk(false);
 const phrase=phrases.find(p=>p.jp===text);if(!phrase)return;
 if(currentAudio){currentAudio.onplaying=null;currentAudio.onerror=null;currentAudio.pause()}
 const panel=$('#audio-panel'),player=$('#audio-player');
 panel.hidden=false;$('#audio-title').textContent=phrase.jp+' • '+phrase.romaji;
 player.src='audio/phrase-'+phrase.id+'.mp3';player.playbackRate=playbackSpeed;player.volume=1;player.muted=false;currentAudio=player;
 notify('กำลังโหลดเสียงญี่ปุ่น…');
 player.onplaying=()=>{animateClerk(clerk);notify('กำลังเล่นเสียง • หากไม่ได้ยิน ให้เพิ่มเสียงและตรวจสอบ Bluetooth')};
 player.onpause=()=>animateClerk(false);player.onended=()=>animateClerk(false);
 player.onerror=()=>{animateClerk(false);notify('โหลดเสียงไม่ได้ กรุณาตรวจอินเทอร์เน็ตแล้วแตะฟังอีกครั้ง')};
 player.play().catch(()=>notify('แตะปุ่ม ▶ ในตัวเล่นเสียงด้านบนเพื่อเริ่มฟัง'));
}
$('#hero-start').addEventListener('click',()=>{setMode('game');$('.tabs').scrollIntoView({behavior:'smooth',block:'start'})});
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function bestScore(){const best=read('tabi-best',{});const value=best&&typeof best==='object'?best[$('#quiz-category').value]:null;$('#best-score').textContent=typeof value==='number'?`คะแนนดีที่สุดหมวดนี้: ${value}/10`:'ลองทำครั้งแรก แล้วเก็บสถิติของคุณ'}
$('#quiz-category').addEventListener('change',bestScore);
function startQuiz(){const cat=$('#quiz-category').value;const pool=phrases.filter(p=>cat==='all'||p.category===cat);let questions=[];while(questions.length<10)questions.push(...shuffle(pool));quiz={questions:questions.slice(0,10),index:0,score:0,answered:false,category:cat};$('.quiz-intro').hidden=true;$('#quiz-game').hidden=false;renderQuestion()}
$('#quiz-start').addEventListener('click',startQuiz);
function renderQuestion(){const q=quiz.questions[quiz.index];const options=shuffle([q,...shuffle(phrases.filter(p=>p.meaning!==q.meaning)).slice(0,3)]);quiz.answered=false;$('#quiz-game').innerHTML=`<div class="quiz-box"><div class="quiz-meta"><span>ข้อ ${quiz.index+1} / 10</span><span>ถูก ${quiz.score} ข้อ</span></div><div class="progress"><span style="width:${quiz.index*10}%"></span></div><p>ประโยคนี้แปลว่าอะไร?</p><h3 class="jp" lang="ja">${q.jp}</h3><button class="listen" id="quiz-listen">◖)) ฟังเสียงคำถาม</button><div class="answers">${options.map(p=>`<button class="answer" data-answer="${p.id}">${p.meaning}</button>`).join('')}</div><div class="feedback" role="status" aria-live="polite"></div><button class="primary" id="quiz-next" hidden>${quiz.index===9?'ดูผลคะแนน':'ข้อถัดไป'} →</button></div>`;$('#quiz-listen').addEventListener('click',()=>speak(q.jp));document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.answer))));$('#quiz-next').addEventListener('click',()=>{quiz.index++;quiz.index===10?finishQuiz():renderQuestion()})}
function answer(id){if(quiz.answered)return;quiz.answered=true;const q=quiz.questions[quiz.index],correct=id===q.id;if(correct)quiz.score++;document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;const bid=Number(b.dataset.answer);if(bid===q.id)b.classList.add('correct');else if(bid===id)b.classList.add('wrong')});$('.feedback').textContent=`${correct?'✓ ถูกต้อง!':'ลองจำประโยคนี้ไว้นะ'} ${q.meaning} • ${q.romaji} • ${q.reading}`;$('#quiz-next').hidden=false;$('#quiz-next').focus()}
function finishQuiz(){const value=read('tabi-best',{}),best=value&&typeof value==='object'&&!Array.isArray(value)?value:{};best[quiz.category]=Math.max(Number(best[quiz.category])||0,quiz.score);write('tabi-best',best);$('#quiz-game').innerHTML=`<div class="quiz-box" style="text-align:center"><div class="eyebrow">PRACTICE MAKES PROGRESS</div><h2>ฝึกครบแล้ว เก่งขึ้นอีกนิด!</h2><div class="result-score">${quiz.score}<small style="font-size:25px"> / 10</small></div><p>${quiz.score>=8?'พร้อมเที่ยวแล้ว! ลองฝึกหมวดอื่นต่อเลย':'ลองฟังและพูดตาม แล้วกลับมาทดสอบอีกครั้งได้เสมอ'}</p><p>คะแนนดีที่สุดหมวด${label(quiz.category)}: ${best[quiz.category]}/10</p><button class="primary" id="quiz-again">ฝึกอีกครั้ง ↗</button> <button class="answer" id="quiz-back">เลือกหมวดใหม่</button></div>`;$('#quiz-again').addEventListener('click',startQuiz);$('#quiz-back').addEventListener('click',()=>{$('.quiz-intro').hidden=false;$('#quiz-game').hidden=true;bestScore()})}
render();bestScore();
initAdventure();setMode('game');

