'use strict';
const collisionDefaults=shopBlocks.map(b=>({...b}));
let shopEditor=null,collisionDrag=null;
function collisionValues(blocks){return blocks.map(b=>({kind:b.kind,x:b.x,y:b.y,w:b.w,h:b.h}))}
function collisionValid(b){return b&&['x','y','w','h'].every(k=>Number.isFinite(b[k]))&&b.x>=0&&b.y>=0&&b.w>=.2&&b.h>=.2&&b.x+b.w<=20&&b.y+b.h<=20}
function collisionApply(blocks){if(!Array.isArray(blocks)||blocks.length!==collisionDefaults.length)return false;const next=collisionDefaults.map(d=>{const v=blocks.find(b=>b.kind===d.kind);return v?{...d,x:v.x,y:v.y,w:v.w,h:v.h}:null});if(!next.every(collisionValid))return false;shopBlocks.splice(0,shopBlocks.length,...next);return true}
function collisionSafePlayer(){if(!shopping||shopCanStand(shopping.x,shopping.y))return;let best=null;for(let y=1;y<=18;y++)for(let x=1;x<=18;x++)if(shopCanStand(x,y)){const distance=Math.hypot(x-shopping.x,y-shopping.y);if(!best||distance<best.distance)best={x,y,distance}}if(best){shopping.x=best.x;shopping.y=best.y}}
function collisionLabel(b,i){return (i+1)+' · '+(b.label||({'right-shelf':'ชั้นด้านขวา','entrance-left':'หน้าร้านซ้าย','entrance-right':'หน้าร้านขวา'}[b.kind]))}
function collisionMount(){const world=$('#shop-world');if(!world)return;world.insertAdjacentHTML('afterend','<div class="collision-tools"><button class="answer" data-collision-action="edit">ปรับ collision</button></div>');if(!shopEditor)return;
world.insertAdjacentHTML('beforeend','<div class="collision-layer">'+shopBlocks.map((b,i)=>'<button type="button" class="collision-rect" data-collision-index="'+i+'" aria-label="'+collisionLabel(b,i)+'" style="left:'+b.x*5+'%;top:'+b.y*5+'%;width:'+b.w*5+'%;height:'+b.h*5+'%"><span>'+ (i+1)+'</span><span class="collision-resize" data-collision-resize aria-label="ย่อหรือขยาย">↘</span></button>').join('')+'</div>');
$('#shopping').insertAdjacentHTML('beforeend','<section class="collision-editor" aria-label="ปรับกรอบ collision"><h3>ปรับพื้นที่ห้ามเดิน</h3><p>ลากกรอบเพื่อย้าย · ลากมุมขวาล่างเพื่อย่อ–ขยาย · เลือกกรอบแล้วใช้ลูกศรขยับได้</p><label>เลือกกรอบ <select data-collision-select>'+shopBlocks.map((b,i)=>'<option value="'+i+'">'+collisionLabel(b,i)+'</option>').join('')+'</select></label><div class="collision-fields">'+[['x','ตำแหน่ง X'],['y','ตำแหน่ง Y'],['w','ความกว้าง'],['h','ความสูง']].map(([k,label])=>'<label>'+label+'<input type="number" min="0" max="20" step="0.1" data-collision-field="'+k+'"></label>').join('')+'</div><p class="collision-status" role="status" aria-live="polite">หน่วยเป็นช่องบนแผนที่ 20 × 20 · เกมหยุดเดินระหว่างปรับ</p><div class="collision-actions"><button class="primary" data-collision-action="save">บันทึกในเบราว์เซอร์นี้</button><button class="answer" data-collision-action="cancel">ยกเลิก</button><button class="answer" data-collision-action="reset">คืนกรอบเริ่มต้น</button></div><label>ค่ากรอบสำหรับส่งให้ปรับเว็บร่วมกัน<textarea data-collision-export readonly rows="5" aria-label="ค่ากรอบ collision"></textarea></label></section>');collisionRefresh()}
function collisionRefresh(preserveField=null){if(!shopEditor)return;const root=$('#shopping'),i=shopEditor.selected,b=shopBlocks[i];root.querySelectorAll('[data-collision-index]').forEach(el=>{const j=Number(el.dataset.collisionIndex),v=shopBlocks[j];Object.assign(el.style,{left:v.x*5+'%',top:v.y*5+'%',width:v.w*5+'%',height:v.h*5+'%'});el.classList.toggle('selected',j===i);el.setAttribute('aria-pressed',String(j===i))});root.querySelector('[data-collision-select]').value=String(i);root.querySelectorAll('[data-collision-field]').forEach(el=>{if(el!==preserveField)el.value=String(Math.round(b[el.dataset.collisionField]*100)/100)});root.querySelector('[data-collision-export]').value=JSON.stringify({version:1,grid:20,blocks:collisionValues(shopBlocks)},null,2)}
function collisionUpdate(values,preserveField=null){const b=shopBlocks[shopEditor.selected];const next={...b,...values};next.x=Math.max(0,Math.min(19.8,next.x));next.y=Math.max(0,Math.min(19.8,next.y));next.w=Math.max(.2,Math.min(20-next.x,next.w));next.h=Math.max(.2,Math.min(20-next.y,next.h));if(!collisionValid(next))return;Object.assign(b,next);collisionRefresh(preserveField)}
function initCollisionEditor(){const saved=read('tabi-collision-v1',null);if(saved&&saved.version===1&&saved.grid===20)collisionApply(saved.blocks);const root=$('#shopping');
root.addEventListener('click',e=>{const action=e.target.closest('[data-collision-action]');if(action){const kind=action.dataset.collisionAction;if(kind==='edit'){if(shopEditor)return;stopShopHold();shopEditor={selected:0,backup:collisionValues(shopBlocks)};renderShopping()}else if(shopEditor){if(kind==='reset'){collisionApply(collisionValues(collisionDefaults));collisionRefresh()}else if(kind==='save'||kind==='cancel'){if(kind==='save')write('tabi-collision-v1',{version:1,grid:20,blocks:collisionValues(shopBlocks)});else collisionApply(shopEditor.backup);shopEditor=null;collisionDrag=null;collisionSafePlayer();renderShopping()}}return}const rect=e.target.closest('[data-collision-index]');if(rect&&shopEditor){shopEditor.selected=Number(rect.dataset.collisionIndex);collisionRefresh()}});
root.addEventListener('input',e=>{if(!shopEditor||!e.target.matches('[data-collision-field]')||e.target.value==='')return;const value=Number(e.target.value);if(Number.isFinite(value))collisionUpdate({[e.target.dataset.collisionField]:value},e.target)});
root.addEventListener('change',e=>{if(!shopEditor)return;if(e.target.matches('[data-collision-select]')){shopEditor.selected=Number(e.target.value);collisionRefresh()}else if(e.target.matches('[data-collision-field]')){const value=Number(e.target.value);if(Number.isFinite(value))collisionUpdate({[e.target.dataset.collisionField]:value})}});
root.addEventListener('pointerdown',e=>{const rect=e.target.closest('[data-collision-index]');if(!rect||!shopEditor)return;e.preventDefault();shopEditor.selected=Number(rect.dataset.collisionIndex);const bounds=$('#shop-world').getBoundingClientRect();collisionDrag={id:e.pointerId,sx:e.clientX,sy:e.clientY,bounds,block:{...shopBlocks[shopEditor.selected]},resize:!!e.target.closest('[data-collision-resize]')};rect.setPointerCapture(e.pointerId);collisionRefresh()});
root.addEventListener('pointermove',e=>{const d=collisionDrag;if(!d||d.id!==e.pointerId||!shopEditor)return;const dx=(e.clientX-d.sx)/d.bounds.width*20,dy=(e.clientY-d.sy)/d.bounds.height*20;const round=v=>Math.round(v*10)/10;collisionUpdate(d.resize?{w:round(d.block.w+dx),h:round(d.block.h+dy)}:{x:round(d.block.x+dx),y:round(d.block.y+dy)})});
const release=e=>{if(collisionDrag?.id===e.pointerId)collisionDrag=null};root.addEventListener('pointerup',release);root.addEventListener('pointercancel',release);root.addEventListener('lostpointercapture',release);
root.addEventListener('keydown',e=>{if(!shopEditor||!e.target.closest('[data-collision-index]'))return;const v={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!v)return;e.preventDefault();const b=shopBlocks[shopEditor.selected],step=e.shiftKey?1:.1;collisionUpdate({x:Math.round((b.x+v[0]*step)*10)/10,y:Math.round((b.y+v[1]*step)*10)/10})})}
