'use strict';
const shoppingProducts=[{index:11,name:'ข้าวกล่องหมู',price:580},{index:5,name:'ข้าวกล่องไก่',price:600}];
let shopping=null;
function shoppingPhrase(id){const p=phrases[id];return '<span lang="ja">'+p.jp+'</span><small>'+p.romaji+'<br>'+p.reading+'</small>'}
function shoppingScene(){return '<img class="shopping-store" src="assets/shopping-store.webp" width="1600" height="900" alt="ภายในร้านสะดวกซื้อ ชั้นข้าวกล่องอยู่ทางซ้าย และเคาน์เตอร์พนักงานอยู่ทางขวา">'}
function shoppingIntro(){return '<h2>เกมเดินซื้อของ · มื้อแรกในญี่ปุ่น</h2>'+shoppingScene()+'<p>เข้าร้าน หยิบข้าวกล่อง แล้วคุยกับพนักงานจนจ่ายเงินเสร็จ</p><p>คุณมีเงินสด 1,000 เยน บัตรจ่ายเงิน และถุงผ้า แต่ไม่มีบัตรสะสมคะแนน เลือกได้ว่าจะอุ่นอาหารและจ่ายแบบไหน</p><button class="primary" data-shop-action="enter">เดินเข้าร้าน →</button><p>สถิติดีที่สุด: '+(Number(read('tabi-shopping-best',0))||0)+' คะแนน</p>'}
function initShopping(){const root=$('#shopping');root.innerHTML=shoppingIntro();root.addEventListener('click',handleShopping);initShopMovement()}
function shoppingStart(){stopShopHold();stopClerkAudio();shopping={stage:'walk',x:5,y:8,leaving:false,product:null,warm:null,payment:null,score:0,penalty:0,done:false,selected:null,hint:false};renderShopping()}
function shoppingQuestion(){switch(shopping.stage){
case 'warm':return {title:'พนักงานถามเรื่องอุ่นอาหาร',npc:37,goal:'เลือกได้ว่าจะอุ่นหรือไม่อุ่นข้าวกล่อง',choices:[{id:43},{id:122},{id:160}],valid:[43,122],why:'はい、お願いします รับให้อุ่น · 温めなくて大丈夫です ไม่ต้องอุ่นก็ได้'};
case 'bag':return {title:'พนักงานถามเรื่องถุง',npc:38,goal:'คุณพกถุงผ้ามาแล้ว ตอบว่าไม่รับถุง',choices:[{id:44},{id:45},{id:46}],valid:[44],why:'袋はいりません = ไม่รับถุง เพราะใช้ถุงที่พกมาเอง'};
case 'loyalty':return {title:'พนักงานถามบัตรสะสมคะแนน',npc:157,goal:'คุณไม่มีบัตรสะสมคะแนน ตอบพนักงาน',choices:[{id:156},{id:158},{id:160}],valid:[158],why:'持っていません = ไม่มี / ไม่ได้พกมา'};
case 'payment':return {title:'เลือกวิธีชำระเงิน',npc:40,goal:'เลือกจ่ายเงินสดหรือบัตรได้ตามต้องการ',choices:[{id:156},{id:46},{id:44}],valid:[156,46],why:'現金でお願いします จ่ายเงินสด · カードでお願いします จ่ายด้วยบัตร'};
case 'tender':return {title:'ยื่นเงินให้พนักงาน',goal:'ยอดรวม '+shopping.product.price+' เยน เลือกธนบัตรที่จ่ายพอ',choices:[{value:500,label:'ยื่น 500 เยน'},{value:1000,label:'ยื่น 1,000 เยน'}],valid:[1000],why:'ธนบัตร 1,000 เยนจ่ายพอสำหรับมื้อนี้'};
case 'change':return {title:'ตรวจเงินทอน',goal:'จ่าย 1,000 เยน ยอดรวม '+shopping.product.price+' เยน ควรได้เงินทอนเท่าไร?',choices:[{value:320,label:'320 เยน'},{value:400,label:'400 เยน'},{value:420,label:'420 เยน'}],valid:[1000-shopping.product.price],why:'1,000 − '+shopping.product.price+' = '+(1000-shopping.product.price)+' เยน'};
case 'receipt':return {title:'ขอใบเสร็จ',goal:'คุณอยากเก็บใบเสร็จไว้ ขอพนักงานอย่างสุภาพ',choices:[{id:160},{id:45},{id:44}],valid:[160],why:'レシートをお願いします = ขอใบเสร็จด้วย'};
case 'thanks':return {title:'ขอบคุณก่อนออกจากร้าน',goal:'ซื้อของเสร็จแล้ว ขอบคุณพนักงาน',choices:[{id:1},{id:35},{id:158}],valid:[1],why:'ありがとうございます = ขอบคุณครับ/ค่ะ'};
}}
function shoppingHud(){return '<div class="shopping-hud"><strong>🏪 '+(shopping.product?shopping.product.name+' · ¥'+shopping.product.price:'เลือกมื้อของคุณ')+'</strong><span>'+shopping.score+' คะแนน</span></div>'}
function shoppingFocus(){const h=$('#shopping-focus');if(h)h.focus()}
function renderShopping(){stopClerkAudio();const root=$('#shopping');let body='';
if(shopping.stage==='walk'){body=shopWorldMarkup()}
else if(shopping.stage==='shelf'){body='<h2 id="shopping-focus" tabindex="-1">เลือกหยิบข้าวกล่องจากชั้น</h2>'+shoppingScene()+'<p>แตะภาพเพื่อหยิบข้าวกล่อง 1 กล่องใส่ตะกร้า ราคานี้เป็นตัวอย่างสำหรับฝึก</p><div class="shopping-products">'+shoppingProducts.map((p,i)=>'<button class="shopping-product" data-shop-product="'+i+'">'+checkoutPricePicture(p.index)+'<span>หยิบ '+p.name+'</span></button>').join('')+'</div>'}
else if(shopping.stage==='basket'){body='<h2 id="shopping-focus" tabindex="-1">ใส่ตะกร้าแล้ว!</h2><div class="shopping-basket">'+checkoutPricePicture(shopping.product.index)+'</div><p>พร้อมแล้ว เดินไปที่เคาน์เตอร์เพื่อคิดเงิน</p><button class="primary" data-shop-action="counter">ไปเคาน์เตอร์ →</button><button class="answer" data-shop-action="reselect">เปลี่ยนข้าวกล่อง</button>'}
else if(shopping.stage==='total'){const priceIndex=shopping.product.price===580?11:5,p=checkoutPhrase(priceIndex);body='<h2 id="shopping-focus" tabindex="-1">พนักงานคิดเงิน</h2>'+checkoutPicture('total','พนักงานแสดงยอดรวมที่เคาน์เตอร์')+'<div class="npc-bubble"><span class="badge">พนักงานพูด</span><p class="jp" lang="ja">合計で'+p.jp+'です。</p><p>'+p.romaji+'</p><p>รวมทั้งหมด '+shopping.product.price+' เยน</p><button class="listen" data-shop-audio="'+p.id+'">◖)) ฟังจำนวนเงิน</button></div><button class="primary" data-shop-action="talk">คุยกับพนักงานต่อ →</button>'}
else if(shopping.stage==='finish'){const best=Math.max(Number(read('tabi-shopping-best',0))||0,shopping.score);write('tabi-shopping-best',best);body='<h2 id="shopping-focus" tabindex="-1">ซื้อของสำเร็จแล้ว!</h2>'+checkoutPricePicture(shopping.product.index)+'<p>'+shopping.product.name+' · '+(shopping.warm?'อุ่นแล้ว':'ไม่อุ่น')+' · '+(shopping.payment==='cash'?'จ่ายเงินสด':'จ่ายด้วยบัตร')+'</p><p>ใช้ถุงที่พกมาเอง และรับใบเสร็จเรียบร้อย</p><div class="result-score">'+shopping.score+'<small> คะแนน</small></div><p>สถิติดีที่สุด '+best+' คะแนน</p><button class="primary" data-shop-action="enter">เล่นอีกครั้ง →</button>'}
else{const q=shoppingQuestion(),npc=q.npc===undefined?null:phrases[q.npc];const art=['warm','bag'].includes(shopping.stage)?wordPicture(shopping.stage==='warm'?'warm':'no-bag',q.title):checkoutPicture(shopping.stage==='loyalty'?'loyalty-card':shopping.stage==='change'?'change':shopping.stage==='receipt'?'receipt':'cash',q.title);body='<h2 id="shopping-focus" tabindex="-1">'+q.title+'</h2><p class="mission-goal">'+q.goal+'</p>'+art+(npc?'<div class="npc-bubble"><span class="badge">พนักงานพูด</span><p class="jp" lang="ja">'+npc.jp+'</p><p>'+npc.romaji+'<br>'+npc.reading+'</p>'+(shopping.hint?'<p>'+npc.meaning+'</p>':'')+'<button class="listen" data-shop-audio="'+npc.id+'">◖)) ฟังพนักงาน</button></div>':'')+'<div class="answers">'+q.choices.map((c,i)=>'<button class="answer '+(shopping.done&&i===shopping.selected?'correct':'')+'" data-shop-choice="'+i+'" '+(shopping.done?'disabled':'')+'>'+(c.id===undefined?c.label:shoppingPhrase(c.id))+'</button>').join('')+'</div><div id="shopping-feedback" role="status" aria-live="polite">'+(shopping.done?'<p>✓ ถูกต้อง! '+q.why+'</p>'+(q.choices[shopping.selected].id!==undefined?'<button class="listen" data-shop-audio="'+q.choices[shopping.selected].id+'">◖)) ฟังคำตอบของคุณ</button>':''):'')+'</div>'+(shopping.done?'<button class="primary" data-shop-action="next">ไปต่อ →</button>':'<button class="hint-button" data-shop-action="hint">ดูคำใบ้ / คำแปล (−20 คะแนน)</button>')}
root.innerHTML=shoppingHud()+body+'<p><button class="hint-button" data-shop-action="restart">เริ่มซื้อของใหม่</button></p>';shoppingFocus()}
function shoppingAnswer(index){if(!shopping||shopping.done)return;const q=shoppingQuestion(),c=q&&q.choices[index];if(!c)return;const value=c.id===undefined?c.value:c.id;if(!q.valid.includes(value)){shopping.penalty+=20;$('#shopping-feedback').textContent='ยังไม่ตรงกับสถานการณ์ ลองตอบใหม่ได้ (−20 คะแนน)';return}shopping.done=true;shopping.selected=index;shopping.score+=Math.max(0,100-shopping.penalty);if(shopping.stage==='warm')shopping.warm=c.id===43;if(shopping.stage==='payment')shopping.payment=c.id===156?'cash':'card';renderShopping()}
function shoppingNext(){if(!shopping||!shopping.done)return;const steps=['warm','bag','loyalty','payment','tender','change','receipt','thanks','finish'];shopping.stage=shopping.stage==='payment'&&shopping.payment==='card'?'receipt':steps[steps.indexOf(shopping.stage)+1];if(shopping.stage==='finish'){shopping.leaving=true;shopping.stage='walk'}shopping.done=false;shopping.selected=null;shopping.penalty=0;shopping.hint=false;renderShopping()}
function handleShopping(e){const move=e.target.closest('[data-shop-move]');if(move){if(Date.now()-shopLastPointer>400)shopMove(move.dataset.shopMove);return}const interact=e.target.closest('[data-shop-interact]');if(interact){shopInteract();return}const audio=e.target.closest('[data-shop-audio]');if(audio){speak(phrases[Number(audio.dataset.shopAudio)].jp,true);return}const product=e.target.closest('[data-shop-product]');if(product&&shopping?.stage==='shelf'){const p=shoppingProducts[Number(product.dataset.shopProduct)];if(p){shopping.product=p;shopping.stage='walk';renderShopping()}return}const choice=e.target.closest('[data-shop-choice]');if(choice){shoppingAnswer(Number(choice.dataset.shopChoice));return}const action=e.target.closest('[data-shop-action]');if(!action)return;switch(action.dataset.shopAction){case 'enter':case 'restart':shoppingStart();break;case 'reselect':if(shopping.stage==='basket'){shopping.stage='shelf';renderShopping()}break;case 'counter':if(shopping.stage==='basket'){shopping.stage='total';renderShopping()}break;case 'talk':if(shopping.stage==='total'){shopping.stage='warm';renderShopping()}break;case 'next':shoppingNext();break;case 'hint':if(shopping&&!shopping.hint&&!shopping.done){shopping.hint=true;shopping.penalty+=20;renderShopping()}break}}

const shopBlocks=[{x:1,y:1,w:3,h:3,label:'🍱 ข้าวกล่อง',kind:'bento'},{x:5,y:1,w:2,h:5,label:'🍪 ขนม',kind:'snacks'},{x:9,y:1,w:2,h:3,label:'👨‍🍳 เคาน์เตอร์',kind:'counter'},{x:1,y:6,w:2,h:2,label:'🥤 เครื่องดื่ม',kind:'drinks'}];
let shopMovementReady=false,shopHold=null,shopLastPointer=0;
function shopCanStand(x,y){return x>=0&&x<12&&y>=0&&y<10&&!shopBlocks.some(b=>x>=b.x&&x<b.x+b.w&&y>=b.y&&y<b.y+b.h)}
function shopNear(kind){const b=shopBlocks.find(b=>b.kind===kind);return shopping&&shopping.x>=b.x-1&&shopping.x<=b.x+b.w&&shopping.y>=b.y-1&&shopping.y<=b.y+b.h}
function shopContext(){if(shopping.leaving)return shopping.y===9&&shopping.x>=4&&shopping.x<=7?'ออกจากร้าน':'เดินไปประตูด้านล่างเพื่อออกจากร้าน';if(shopNear('bento'))return 'เลือกหยิบข้าวกล่อง';if(shopNear('counter'))return shopping.product?'คุยกับพนักงาน / คิดเงิน':'ต้องหยิบข้าวกล่องก่อน';return shopping.product?'เดินไปหาเคาน์เตอร์ด้านขวาบน':'เดินไปชั้นข้าวกล่องด้านซ้ายบน'}
function shopWorldMarkup(){return '<h2 id="shopping-focus" tabindex="-1">'+(shopping.leaving?'เดินออกจากร้าน':'เดินเลือกซื้อของ')+'</h2><p>ลูกศร / WASD เพื่อเดิน · E หรือ Space เพื่อหยิบของและคุย · มือถือใช้ปุ่มด้านล่าง</p><div id="shop-world" class="shop-world" tabindex="0" role="application" aria-label="แผนที่ร้านสะดวกซื้อ ใช้ลูกศรเดิน และ E เพื่อหยิบของหรือคุย">'+shopBlocks.map(b=>'<div class="shop-fixture '+b.kind+'" style="left:'+b.x/12*100+'%;top:'+b.y/10*100+'%;width:'+b.w/12*100+'%;height:'+b.h/10*100+'%"><span>'+b.label+'</span>'+(b.kind==='bento'?'<span class="shop-stock">🍱 🍱<br>🍱 🍱</span>':b.kind==='snacks'?'<span class="shop-stock">🍪<br>🍫<br>🍬</span>':'')+'</div>').join('')+'<div class="shop-door">🚪 ทางเข้า / ออก</div><div id="shop-player" class="shop-player" style="left:'+((shopping.x+.5)/12*100)+'%;top:'+((shopping.y+.5)/10*100)+'%" role="img" aria-label="ตัวละครของคุณ"><span class="shop-avatar">🧑</span><span class="shop-player-label">คุณ'+(shopping.product?' 🍱':'')+'</span></div></div><p id="shop-context" class="shop-context" role="status" aria-live="polite">'+shopContext()+'</p><div class="shop-controls" aria-label="ปุ่มควบคุมตัวละคร"><div class="shop-dpad"><button data-shop-move="up" aria-label="เดินขึ้น">▲</button><button data-shop-move="left" aria-label="เดินซ้าย">◀</button><button data-shop-move="down" aria-label="เดินลง">▼</button><button data-shop-move="right" aria-label="เดินขวา">▶</button></div><button class="primary" data-shop-interact>หยิบ / คุย (E)</button></div>'}
function shopMove(direction){if(!shopping||shopping.stage!=='walk'||$('#shopping-panel').hidden)return;const delta={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[direction];if(!delta)return;const x=shopping.x+delta[0],y=shopping.y+delta[1];if(shopCanStand(x,y)){shopping.x=x;shopping.y=y;const player=$('#shop-player');player.style.left=((x+.5)/12*100)+'%';player.style.top=((y+.5)/10*100)+'%';player.dataset.facing=direction}$('#shop-context').textContent=shopContext()}
function shopInteract(){if(!shopping||shopping.stage!=='walk')return;stopShopHold();if(shopping.leaving){if(shopping.y===9&&shopping.x>=4&&shopping.x<=7){shopping.stage='finish';renderShopping()}else $('#shop-context').textContent=shopContext();return}if(shopNear('counter')&&shopping.product){shopping.stage='total';renderShopping()}else if(shopNear('bento')){shopping.stage='shelf';renderShopping()}else $('#shop-context').textContent=shopContext()}
function stopShopHold(){if(shopHold!==null){clearInterval(shopHold);shopHold=null}}
function initShopMovement(){if(shopMovementReady)return;shopMovementReady=true;document.addEventListener('keydown',e=>{if(!shopping||shopping.stage!=='walk'||$('#shopping-panel').hidden||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const k=e.key.toLowerCase(),dir={arrowup:'up',w:'up',arrowdown:'down',s:'down',arrowleft:'left',a:'left',arrowright:'right',d:'right'}[k];if(dir){e.preventDefault();shopMove(dir)}else if(k==='e'||k===' '){e.preventDefault();if(!e.repeat)shopInteract()}});$('#shopping').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-shop-move]');if(!b)return;e.preventDefault();shopLastPointer=Date.now();stopShopHold();shopMove(b.dataset.shopMove);shopHold=setInterval(()=>{if(!shopping||shopping.stage!=='walk'||$('#shopping-panel').hidden){stopShopHold();return}shopLastPointer=Date.now();shopMove(b.dataset.shopMove)},150)});document.addEventListener('pointerup',stopShopHold);document.addEventListener('pointercancel',stopShopHold);window.addEventListener('blur',stopShopHold);document.addEventListener('visibilitychange',stopShopHold)}
