'use strict';
const shoppingProducts=[{index:11,name:'ข้าวกล่องหมู',price:580},{index:5,name:'ข้าวกล่องไก่',price:600}];
let shopping=null;
function shoppingPhrase(id){const p=phrases[id];return '<span lang="ja">'+p.jp+'</span><small>'+p.romaji+'<br>'+p.reading+'</small>'}
function shoppingScene(){return '<img class="shopping-store" src="assets/shopping-store.webp" width="1600" height="900" alt="ภายในร้านสะดวกซื้อ ชั้นข้าวกล่องอยู่ทางซ้าย และเคาน์เตอร์พนักงานอยู่ทางขวา">'}
function shoppingIntro(){return '<h2>เกมเดินซื้อของ · มื้อแรกในญี่ปุ่น</h2>'+shoppingScene()+'<p>เข้าร้าน หยิบข้าวกล่อง แล้วคุยกับพนักงานจนจ่ายเงินเสร็จ</p><p>คุณมีเงินสด 1,000 เยน บัตรจ่ายเงิน และถุงผ้า แต่ไม่มีบัตรสะสมคะแนน เลือกได้ว่าจะอุ่นอาหารและจ่ายแบบไหน</p><button class="primary" data-shop-action="enter">เดินเข้าร้าน →</button><p>สถิติดีที่สุด: '+(Number(read('tabi-shopping-best',0))||0)+' คะแนน</p>'}
function initShopping(){const root=$('#shopping');root.innerHTML=shoppingIntro();root.addEventListener('click',handleShopping)}
function shoppingStart(){stopClerkAudio();shopping={stage:'shelf',product:null,warm:null,payment:null,score:0,penalty:0,done:false,selected:null,hint:false};renderShopping()}
function shoppingQuestion(){switch(shopping.stage){
case 'warm':return {title:'พนักงานถามเรื่องอุ่นอาหาร',npc:37,goal:'เลือกได้ว่าจะอุ่นหรือไม่อุ่นข้าวกล่อง',choices:[{id:43},{id:122},{id:160}],valid:[43,122],why:'はい、お願いします รับให้อุ่น · 温めなくて大丈夫です ไม่ต้องอุ่นก็ได้'};
case 'bag':return {title:'พนักงานถามเรื่องถุง',npc:38,goal:'คุณพกถุงผ้ามาแล้ว ตอบว่าไม่รับถุง',choices:[{id:44},{id:45},{id:46}],valid:[44],why:'袋はいりません = ไม่รับถุง เพราะใช้ถุงที่พกมาเอง'};
case 'loyalty':return {title:'พนักงานถามบัตรสะสมคะแนน',npc:157,goal:'คุณไม่มีบัตรสะสมคะแนน ตอบพนักงาน',choices:[{id:156},{id:158},{id:160}],valid:[158],why:'持っていません = ไม่มี / ไม่ได้พกมา'};
case 'payment':return {title:'เลือกวิธีชำระเงิน',npc:40,goal:'เลือกจ่ายเงินสดหรือบัตรได้ตามต้องการ',choices:[{id:156},{id:46},{id:44}],valid:[156,46],why:'現金でお願いします จ่ายเงินสด · カードでお願いします จ่ายด้วยบัตร'};
case 'tender':return {title:'ยื่นเงินให้พนักงาน',goal:'ยอดรวม '+shopping.product.price+' เยน เลือกธนบัตรที่จ่ายพอ',choices:[{value:500,label:'ยื่น 500 เยน'},{value:1000,label:'ยื่น 1,000 เยน'}],valid:[1000],why:'ธนบัตร 1,000 เยนจ่ายพอสำหรับมื้อนี้'};
case 'change':return {title:'ตรวจเงินทอน',goal:'จ่าย 1,000 เยน ยอดรวม '+shopping.product.price+' เยน ควรได้เงินทอนเท่าไร?',choices:[{value:320,label:'320 เยน'},{value:400,label:'400 เยน'},{value:420,label:'420 เยน'}],valid:[1000-shopping.product.price],why:'1,000 − '+shopping.product.price+' = '+(1000-shopping.product.price)+' เยน'};
case 'receipt':return {title:'ขอใบเสร็จ',goal:'คุณอยากเก็บใบเสร็จไว้ ขอพนักงานอย่างสุภาพ',choices:[{id:160},{id:45},{id:44}],valid:[160],why:'レシートをお願いします = ขอใบเสร็จด้วย'};
case 'thanks':return {title:'ขอบคุณก่อนออกจากร้าน',goal:'ซื้อของเสร็จแล้ว ขอบคุณพนักงาน',choices:[{id:1},{id:35},{id:158}],valid:[1],why:'ありがとうございます = ขอบคุณครับ/ค่ะ'};
}}
function shoppingHud(){return '<div class="shopping-hud"><strong>🏪 '+(shopping.product?shopping.product.name+' · ¥'+shopping.product.price:'เลือกมื้อของคุณ')+'</strong><span>'+shopping.score+' คะแนน</span></div>'}
function shoppingFocus(){const h=$('#shopping-focus');if(h)h.focus()}
function renderShopping(){stopClerkAudio();const root=$('#shopping');let body='';
if(shopping.stage==='shelf'){body='<h2 id="shopping-focus" tabindex="-1">เลือกหยิบข้าวกล่องจากชั้น</h2>'+shoppingScene()+'<p>แตะภาพเพื่อหยิบข้าวกล่อง 1 กล่องใส่ตะกร้า ราคานี้เป็นตัวอย่างสำหรับฝึก</p><div class="shopping-products">'+shoppingProducts.map((p,i)=>'<button class="shopping-product" data-shop-product="'+i+'">'+checkoutPricePicture(p.index)+'<span>หยิบ '+p.name+'</span></button>').join('')+'</div>'}
else if(shopping.stage==='basket'){body='<h2 id="shopping-focus" tabindex="-1">ใส่ตะกร้าแล้ว!</h2><div class="shopping-basket">'+checkoutPricePicture(shopping.product.index)+'</div><p>พร้อมแล้ว เดินไปที่เคาน์เตอร์เพื่อคิดเงิน</p><button class="primary" data-shop-action="counter">ไปเคาน์เตอร์ →</button><button class="answer" data-shop-action="reselect">เปลี่ยนข้าวกล่อง</button>'}
else if(shopping.stage==='total'){const priceIndex=shopping.product.price===580?11:5,p=checkoutPhrase(priceIndex);body='<h2 id="shopping-focus" tabindex="-1">พนักงานคิดเงิน</h2>'+checkoutPicture('total','พนักงานแสดงยอดรวมที่เคาน์เตอร์')+'<div class="npc-bubble"><span class="badge">พนักงานพูด</span><p class="jp" lang="ja">合計で'+p.jp+'です。</p><p>'+p.romaji+'</p><p>รวมทั้งหมด '+shopping.product.price+' เยน</p><button class="listen" data-shop-audio="'+p.id+'">◖)) ฟังจำนวนเงิน</button></div><button class="primary" data-shop-action="talk">คุยกับพนักงานต่อ →</button>'}
else if(shopping.stage==='finish'){const best=Math.max(Number(read('tabi-shopping-best',0))||0,shopping.score);write('tabi-shopping-best',best);body='<h2 id="shopping-focus" tabindex="-1">ซื้อของสำเร็จแล้ว!</h2>'+checkoutPricePicture(shopping.product.index)+'<p>'+shopping.product.name+' · '+(shopping.warm?'อุ่นแล้ว':'ไม่อุ่น')+' · '+(shopping.payment==='cash'?'จ่ายเงินสด':'จ่ายด้วยบัตร')+'</p><p>ใช้ถุงที่พกมาเอง และรับใบเสร็จเรียบร้อย</p><div class="result-score">'+shopping.score+'<small> คะแนน</small></div><p>สถิติดีที่สุด '+best+' คะแนน</p><button class="primary" data-shop-action="enter">เล่นอีกครั้ง →</button>'}
else{const q=shoppingQuestion(),npc=q.npc===undefined?null:phrases[q.npc];const art=['warm','bag'].includes(shopping.stage)?wordPicture(shopping.stage==='warm'?'warm':'no-bag',q.title):checkoutPicture(shopping.stage==='loyalty'?'loyalty-card':shopping.stage==='change'?'change':shopping.stage==='receipt'?'receipt':'cash',q.title);body='<h2 id="shopping-focus" tabindex="-1">'+q.title+'</h2><p class="mission-goal">'+q.goal+'</p>'+art+(npc?'<div class="npc-bubble"><span class="badge">พนักงานพูด</span><p class="jp" lang="ja">'+npc.jp+'</p><p>'+npc.romaji+'<br>'+npc.reading+'</p>'+(shopping.hint?'<p>'+npc.meaning+'</p>':'')+'<button class="listen" data-shop-audio="'+npc.id+'">◖)) ฟังพนักงาน</button></div>':'')+'<div class="answers">'+q.choices.map((c,i)=>'<button class="answer '+(shopping.done&&i===shopping.selected?'correct':'')+'" data-shop-choice="'+i+'" '+(shopping.done?'disabled':'')+'>'+(c.id===undefined?c.label:shoppingPhrase(c.id))+'</button>').join('')+'</div><div id="shopping-feedback" role="status" aria-live="polite">'+(shopping.done?'<p>✓ ถูกต้อง! '+q.why+'</p>'+(q.choices[shopping.selected].id!==undefined?'<button class="listen" data-shop-audio="'+q.choices[shopping.selected].id+'">◖)) ฟังคำตอบของคุณ</button>':''):'')+'</div>'+(shopping.done?'<button class="primary" data-shop-action="next">ไปต่อ →</button>':'<button class="hint-button" data-shop-action="hint">ดูคำแปลคำถาม (−20 คะแนน)</button>')}
root.innerHTML=shoppingHud()+body+'<p><button class="hint-button" data-shop-action="restart">เริ่มซื้อของใหม่</button></p>';shoppingFocus()}
function shoppingAnswer(index){if(!shopping||shopping.done)return;const q=shoppingQuestion(),c=q&&q.choices[index];if(!c)return;const value=c.id===undefined?c.value:c.id;if(!q.valid.includes(value)){shopping.penalty+=20;$('#shopping-feedback').textContent='ยังไม่ตรงกับสถานการณ์ ลองตอบใหม่ได้ (−20 คะแนน)';return}shopping.done=true;shopping.selected=index;shopping.score+=Math.max(0,100-shopping.penalty);if(shopping.stage==='warm')shopping.warm=c.id===43;if(shopping.stage==='payment')shopping.payment=c.id===156?'cash':'card';renderShopping()}
function shoppingNext(){if(!shopping||!shopping.done)return;const steps=['warm','bag','loyalty','payment','tender','change','receipt','thanks','finish'];shopping.stage=shopping.stage==='payment'&&shopping.payment==='card'?'receipt':steps[steps.indexOf(shopping.stage)+1];shopping.done=false;shopping.selected=null;shopping.penalty=0;shopping.hint=false;renderShopping()}
function handleShopping(e){const audio=e.target.closest('[data-shop-audio]');if(audio){speak(phrases[Number(audio.dataset.shopAudio)].jp,true);return}const product=e.target.closest('[data-shop-product]');if(product&&shopping?.stage==='shelf'){const p=shoppingProducts[Number(product.dataset.shopProduct)];if(p){shopping.product=p;shopping.stage='basket';renderShopping()}return}const choice=e.target.closest('[data-shop-choice]');if(choice){shoppingAnswer(Number(choice.dataset.shopChoice));return}const action=e.target.closest('[data-shop-action]');if(!action)return;switch(action.dataset.shopAction){case 'enter':case 'restart':shoppingStart();break;case 'reselect':if(shopping.stage==='basket'){shopping.stage='shelf';renderShopping()}break;case 'counter':if(shopping.stage==='basket'){shopping.stage='total';renderShopping()}break;case 'talk':if(shopping.stage==='total'){shopping.stage='warm';renderShopping()}break;case 'next':shoppingNext();break;case 'hint':if(shopping&&!shopping.hint&&!shopping.done){shopping.hint=true;shopping.penalty+=20;renderShopping()}break}}
